<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
?>
<p><h2><align = "center">Rodent time!</center></h2></p>

<align ="center"><IMG SRC="https://sites.google.com/site/ratlandusa/home/Ratland.png" ALT="" HEIGHT="500" WIDTH="500"></align>

<p>
<?php
  echo '<a  href="'.$this->webroot.'/rodent/unu/init" >unu application pipeline</a>';
?><br />

<?php
  echo '<a  href="'.$this->webroot.'/rodent/reg/init" >Registration pipeline</a>';
?><br />

<?php
  echo '<a  href="'.$this->webroot.'/rodent/ss/init" >Skullstrip pipeline</a>';
?><br />

<?php
  echo '<a  href="'.$this->webroot.'/rodent/a/init" >Atlas pipeline</a>';
?><br />

<?php
  echo '<a  href="'.$this->webroot.'/rodent/as/init" >Atlas Segmentation pipeline</a>';
?><br />

<?php
  echo '<a  href="'.$this->webroot.'/rodent/w/init" >Warp pipeline</a>';
?><br />

<?php
  echo '<a  href="'.$this->webroot.'/rodent/st/init" >Stat pipeline</a>';
?><br />
</p>
