<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.timepicker-addon.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/unu/unu.init.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.smartWizard-2.0.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/unu/unu.init.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.timepicker-addon.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.smartWizard-2.0.css" />


<?php
$processSteps = array();
$processSteps[1] = array('title'=>'Input', 'subtitle'=>'select input images');
$processSteps[2] = array('title'=>'Output', 'subtitle'=>'select output folder');
$processSteps[3] = array('title'=>'Parameters', 'subtitle'=>'specify parameter values');
?>

<div id="wizard" class="swMain">
  <ul>
<?php
  foreach($processSteps as $i => $processStep)
    {
    echo '<li>';
    echo '  <a href="#step-'.$i.'">';
    echo '    <span class="stepDesc">';
    echo '      '.$i.') '.$processStep["title"].'<br/>';
    echo '      <small>'.$processStep["subtitle"].'</small>';
    echo '    </span>';
    echo '  </a>';
    echo '</li>';
    }
?>
  </ul>

    
  <div id="step-1">
      <h2 class="StepTitle">Input</h2>
      <br/><b>Please specify the Midas item containing an image to use as input.</b>
      <br/>
      <br/>

      <?php
        echo '<div id="midas_rodent_unu_browseImageFile" class="genericBigButton ">';
          echo "<a  ><img  alt='' src='{$this->coreWebroot}/public/images/FileTree/file.png'/>";
          echo 'Browse';
          echo "</a>";
        echo '</div>';
        ?>
      <br/>
      <b>Selected Item:</b> <span id="midas_rodent_unu_selectedImage"><?php echo (isset($this->itemDao))? $this->itemDao->getName():'None'?></span>
      <input type="hidden" id="midas_rodent_unu_selectedImageId" value="<?php echo (isset($this->itemDao))? $this->itemDao->getKey():''?>"/>

  </div>

  <div id="step-2">
      <h2 class="StepTitle">Output</h2>
      <br/><b>Please specify the Midas folder where the output will be uploaded.</b>
      <br/>
      <br/>

      <?php
        echo '<div id="midas_rodent_unu_browseOutputFolder" class="genericBigButton ">';
          echo "<a  ><img  alt='' src='{$this->coreWebroot}/public/images/FileTree/directory.png'/>";
          echo 'Browse';
          echo "</a>";
        echo '</div>';
        ?>

      <br/>
      <b>Selected Folder:</b> <span id="midas_rodent_unu_selectedFolder"></span>
      <input type="hidden" id="midas_rodent_unu_selectedFolderId" value=""/>

  </div>
    
    
    
    
  <div id="step-3">
      <h2 class="StepTitle">Parameters</h2>
      <br/>
      <b>Please set the value of parameters A and P.</b><br/><br/>
      <br/>
      <br/>
      
      <strong>A</strong><input type="text" id="midas_rodent_unu_aValue" name="aValue"/>
      <br/>
      <strong>P</strong><input type="text" id="midas_rodent_unu_pValue" name="pValue"/>
      
  </div>
</div>





