<?php
/*=========================================================================
MIDAS Server
Copyright (c) Kitware SAS. 20 rue de la Villette. All rights reserved.
69328 Lyon, FRANCE.

See Copyright.txt for details.
This software is distributed WITHOUT ANY WARRANTY; without even
the implied warranty of MERCHANTABILITY or FITNESS FOR A PARTICULAR
PURPOSE.  See the above copyright notices for more information.
=========================================================================*/
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.form.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.timepicker-addon.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/common/common.rodent.js');
$this->headScript()->appendFile($this->moduleWebroot . '/public/js/common/pipeline.init.js');
$this->headScript()->appendFile($this->coreWebroot . '/public/js/jquery/jquery.smartWizard-2.0.js');
$this->headScript()->appendFile($this->apiWebroot.'/public/js/common/common.ajaxapi.js');
?>
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/common/common.rodent.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->moduleWebroot?>/public/css/unu/unu.init.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.timepicker-addon.css" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->coreWebroot?>/public/css/jquery/jquery.smartWizard-2.0.css" />


<?php
$prefix = $this->inputs['prefix'];
$processSteps = $this->processSteps;
?>
<div id="wizard" class="swMain">
  <ul>
<?php
// this can be pulled out into a method
  foreach($processSteps as $i => $processStep)
    {
    echo '<li>';
    echo '  <a href="#step-'.$i.'">';
    echo '    <span class="stepDesc">';
    echo '      '.$i.') '.$processStep["title"].'<br/>';
    if(array_key_exists("subtitle", $processStep))
      {
      echo '      <small>'.$processStep["subtitle"].'</small>';
      }
    echo '    </span>';
    echo '  </a>';
    echo '</li>';
    }
?>
  </ul>

    
<?php

// this stuff can also be pulled out into a method
  foreach($processSteps as $i => $processStep)
    {
    echo '<div id="step-'.$i.'">';

    if($processStep['type'] === "cases") 
      {
      $casesSelection = $this->inputs['cases'];
      $id = $casesSelection['id'];
      $label = $casesSelection['label'];
      echo '<h2 class="StepTitle">'.$label.'</h2><br/><br/>';
      echo '<div>';
      echo '<span id="'. $prefix . $id . "_name" .'"></span>';
      echo '<div id="'. $prefix . $id . "_button" . '" class="genericBigButton ">';
      echo "<a  ><img  alt='' src='{$this->coreWebroot}/public/images/FileTree/directory.png'/>";
      echo 'Browse';
      echo "</a>";
      echo '</div>';  
//      echo '<input type="hidden" id="'. $prefix . $id .'_type" value="cases"/>';
      echo '<input type="hidden" id="'. $prefix . $id .'" class="pipelineparameter" value=""/>';
      echo '</div><br/>';
      }
    if($processStep['type'] === "multiItems") 
      {
      $multiItemsSelection = $this->inputs['multiItems'];
      $id = $processStep['id'];
      $label = $processStep['label'];
      echo '<h2 class="StepTitle">'.$label.'</h2><br/><br/>';
      echo '<div>';
      echo '<span id="'. $prefix . $id . "_name" .'"></span>';
      echo '<div id="'. $prefix . $id . "_button" . '" class="genericBigButton ">';
      echo "<a  ><img  alt='' src='{$this->coreWebroot}/public/images/FileTree/directory.png'/>";
      echo 'Browse';
      echo "</a>";
      echo '</div>';  
      echo '<input type="hidden" id="'. $prefix . $id .'" class="pipelineparameter" value=""/>';
      echo '</div><br/>';
      }
      
    if($processStep['type'] === "singleItems") 
      {
      $singleItemsSelections = $this->inputs['singleItems'];?>
      <h2 class="StepTitle">Items</h2>
      <br/><b>Please select a Midas item for each input.</b>
      <br/>
      <br/>
      <?php
      foreach($singleItemsSelections as $itemId => $itemInfo)
        {
        echo '<div>';
        echo '<b>'.$itemInfo['label'].':</b> <span id="'. $prefix . $itemId . "_name" .'"></span>';
        echo '<div id="'. $prefix . $itemId . "_button" . '" class="genericBigButton ">';
        echo "<a  ><img  alt='' src='{$this->coreWebroot}/public/images/FileTree/directory.png'/>";
        echo 'Browse';
        echo "</a>";
        echo '</div>';  
        echo '<input type="hidden" id="'. $prefix . $itemId .'" class="pipelineparameter" value=""/>';
        echo '</div><br/>';
        }
      }
      
    if($processStep['type'] === "parameters") 
      { ?>
      <h2 class="StepTitle">Parameters</h2>
      <br/>
      <b>Please set the parameter values.</b><br/><br/>
      <?php
      $parameters = $this->inputs['parameters'];
      foreach($parameters as $parameterId => $parameterDef)
        {
        if($parameterDef['type'] === 'boolean')
          {
          echo '<input type="checkbox" class="pipelineparameter" id="'. $prefix . $parameterId .'"';
          if(isset($parameterDef['default']) && $parameterDef['default'] === true)
            {
            echo ' checked="checked" ';
            }
          echo '>'.$parameterDef['label'] . '<br/>';
          }
        elseif($parameterDef['type'] === 'text' )
          {
          echo '<input type="text" class="pipelineparameter" id="'. $prefix . $parameterId .'" ';
          if(isset($parameterDef['default']))
            {
            echo ' value="'.$parameterDef['default'].'" ';
            }
          echo '>'.$parameterDef['label'] . '<br/>';
          }
        elseif($parameterDef['type'] === 'integer')
          {
          echo '<input type="text" class="pipelineparameter" id="'. $prefix . $parameterId .'" >'.$parameterDef['label'] . '<br/>';
          }
        elseif($parameterDef['type'] === 'select')
          {
          echo '<select class="pipelineparameter" id="'. $prefix . $parameterId .'">';
          foreach($parameterDef['options'] as $option)
            {
            echo '<option value="'.$option.'">'.$option.'</option>';
            }
          echo "</select>".$parameterDef['label']."<br/>";
          }
        }
      }
      
    echo '</div>';
    }
?>
    
</div>





